wait with comment and error rename directory backup to out prepare for crypto and connection yml core/library/test/sandbox#1

diff --git a/atomyze-bft-2.3-devel/tool/data/bin/entrypoint b/atomyze-bft-2.3-devel/tool/data/bin/entrypoint
--- a/atomyze-bft-2.3-devel/tool/data/bin/entrypoint
+++ b/atomyze-bft-2.3-devel/tool/data/bin/entrypoint
@@ -2,5 +2,11 @@
 
 while true
 do
-    steps
+    if ! steps
+    then
+        echo ""
+        echo "-- ERROR: -----------------------------------"
+        echo ""
+        sleep 30
+    fi
 done
